
package lyn.ssh.service.lawyee.webservice.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LicenseServiceService", targetNamespace = "http://ws.service.lms.lenchy.com/", wsdlLocation = "http://test.oa.acla.org.cn/ws/licenseService?wsdl")
public class LicenseServiceService
    extends Service
{

    private final static URL LICENSESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException LICENSESERVICESERVICE_EXCEPTION;
    private final static QName LICENSESERVICESERVICE_QNAME = new QName("http://ws.service.lms.lenchy.com/", "LicenseServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://test.oa.acla.org.cn/ws/licenseService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LICENSESERVICESERVICE_WSDL_LOCATION = url;
        LICENSESERVICESERVICE_EXCEPTION = e;
    }

    public LicenseServiceService() {
        super(__getWsdlLocation(), LICENSESERVICESERVICE_QNAME);
    }

    public LicenseServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LICENSESERVICESERVICE_QNAME, features);
    }

    public LicenseServiceService(URL wsdlLocation) {
        super(wsdlLocation, LICENSESERVICESERVICE_QNAME);
    }

    public LicenseServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LICENSESERVICESERVICE_QNAME, features);
    }

    public LicenseServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LicenseServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ILicenseService
     */
    @WebEndpoint(name = "LicenseServicePort")
    public ILicenseService getLicenseServicePort() {
        return super.getPort(new QName("http://ws.service.lms.lenchy.com/", "LicenseServicePort"), ILicenseService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ILicenseService
     */
    @WebEndpoint(name = "LicenseServicePort")
    public ILicenseService getLicenseServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.service.lms.lenchy.com/", "LicenseServicePort"), ILicenseService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LICENSESERVICESERVICE_EXCEPTION!= null) {
            throw LICENSESERVICESERVICE_EXCEPTION;
        }
        return LICENSESERVICESERVICE_WSDL_LOCATION;
    }

}
